#!/usr/bin/env bash
# Copyright (c) 2026 Relax Authors. All Rights Reserved.

export PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
export MEGATRON="${MEGATRON:-}"
export RELAX_PYTHON="${RELAX_PYTHON:-python3}"
export PYTHONPATH="${PROJECT_ROOT}${MEGATRON:+:${MEGATRON}}"
export STUDENT_MODEL_PATH="${STUDENT_MODEL_PATH:?Set STUDENT_MODEL_PATH}"
export TEACHER_MODEL_PATH="${TEACHER_MODEL_PATH:-${STUDENT_MODEL_PATH}}"
export SDPO_DATA_ROOT="${SDPO_DATA_ROOT:-}"
export ACTOR_GPUS="${ACTOR_GPUS:-2}"
export ROLLOUT_GPUS="${ROLLOUT_GPUS:-1}"
export TEACHER_GPUS="${TEACHER_GPUS:-1}"
export TP_SIZE="${TP_SIZE:-2}"
export CP_SIZE="${CP_SIZE:-1}"
export ROLLOUT_ENGINE_GPUS="${ROLLOUT_ENGINE_GPUS:-${ROLLOUT_GPUS}}"
export TEACHER_ENGINE_GPUS="${TEACHER_ENGINE_GPUS:-${TEACHER_GPUS}}"
export NUM_GPUS="${NUM_GPUS:-${ACTOR_GPUS}}"
export NUM_ROLLOUT="${NUM_ROLLOUT:-2}"
export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-1}"
export N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-2}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-2}"
export MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU:-18944}"
export RELAX_OPD_PER_POS_TOKEN_IDS=1
